name: passed secret
on:
  workflow_call:
    secrets:
      access-token:
        description: 'A token passed from the caller workflow'
        required: false
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Access secret
        run: echo "The secret is ${{ secrets.MY_SECRET }}"
